{% set name = "libtinyiiod" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/analogdevicesinc/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0b9bc22b2e0090b905fa369fcc652fe3522a68b0aad5ded1d30a1464058596d2

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libtinyiiod', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]

test:
  commands:
    # verify that headers get installed
    - test -f $PREFIX/include/tinyiiod/tinyiiod.h  # [not win]
    - test -f $PREFIX/include/tinyiiod/compat.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\tinyiiod\tinyiiod.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\tinyiiod\compat.h exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/tinyiiod${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\tinyiiod.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\tinyiiod.lib exit 1  # [win]

    # verify cmake configs get installed
    - test -f $PREFIX/lib/cmake/tinyiiod/tinyiiodTargets.cmake  # [not win]
    - test -f $PREFIX/lib/cmake/tinyiiod/tinyiiodTargets-release.cmake  # [not win]
    - test -f $PREFIX/lib/cmake/tinyiiod/tinyiiodConfigVersion.cmake  # [not win]
    - test -f $PREFIX/lib/cmake/tinyiiod/tinyiiodConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\tinyiiod\\tinyiiodTargets.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\tinyiiod\\tinyiiodTargets-release.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\tinyiiod\\tinyiiodConfigVersion.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\tinyiiod\\tinyiiodConfig.cmake exit 1  # [win]

about:
  home: https://github.com/analogdevicesinc/libtinyiiod
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'Tiny IIO Daemon Library'
  description: |
    Tiny implementation of IIO Daemon (iiod) for baremetal systems and other applications
  doc_url: https://wiki.analog.com/resources/no-os/tinyiiod_demo
  dev_url: https://github.com/analogdevicesinc/libtinyiiod

extra:
  recipe-maintainers:
    - tfcollins
